# Generated by Django 2.2.6 on 2019-10-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('memo', models.CharField(max_length=100)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Coffee')),
            ],
        ),
    ]
